name: Build and Publish

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

jobs:
  nox-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Install Deps
        run: sudo apt-get update && sudo apt-get install -y libosmesa6-dev
      # https://github.com/mcfletch/pyopengl/issues/90
      - name: Ubuntu PyOpenGL Fix
        run: sudo ln -s /usr/lib/x86_64-linux-gnu/libglut.so.3.12 /usr/lib/x86_64-linux-gnu/libglut.so.3
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.8"
          cache: true
      - name: Run tests
        run: |
          pipx run nox -s lint test
        env:
          MUJOCO_GL: osmesa
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build Distribution
        run: pdm build
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
