name: Test

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  nox-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8"]
        os: [ubuntu-latest]
    permissions:
      contents: read
    steps:
      - name: Install Deps
        run: sudo apt-get update && sudo apt-get install -y libosmesa6-dev
      # https://github.com/mcfletch/pyopengl/issues/90
      - name: Ubuntu PyOpenGL Fix
        run: sudo ln -s /usr/lib/x86_64-linux-gnu/libglut.so.3.12 /usr/lib/x86_64-linux-gnu/libglut.so.3
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
      - name: Run tests
        run: |
          pipx run nox
        env:
          MUJOCO_GL: osmesa
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
